name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan/validate output'
author: 'kgrubb'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan, validate]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output. This must be trimmed to at least 128 KiB. Required for non plan commenter types.'
    required: false
  commenter_plan_path:
    description: 'The tfplan file. Required if commenter input is not set for plan commenter types.'
    required: false
  commenter_exitcode:
    description: 'The exit code from a previous step output.'
    required: true
  terraform_version:
    description: 'The version of terraform from the workflow.'
    required: false
    default: '1.5.6'
  use_beta_version:
    description: 'Whether to use the beta version of the commenter.'
    required: false
    default: 'false'
  project:
    description: 'The project name to use in the comment.'
    required: false
outputs:
  comment_id:
    description: ID of created comment
    value: ${{ steps.commenter-plan.outputs.comment_id || steps.commenter.outputs.comment_id }}
  comment_url:
    description: URL to created comment
    value: ${{ steps.commenter-plan.outputs.comment_url || steps.commenter.outputs.comment_url }}
runs:
  using: "composite"
  steps:
    - name: Set Terraform Version if inputs.terraform_version is Empty # Until https://github.com/actions/runner/issues/924 is fixed
      id: terraform_version
      shell: bash
      run: |
        if [[ -z ${{ inputs.terraform_version }} ]]; then
          echo "version=1.5.6" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.terraform_version }}" >> $GITHUB_OUTPUT
        fi

    - name: Run commenter image (plan)
      id: commenter-plan
      if: ${{ inputs.commenter_type == 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        COMMENTER_PLAN_FILE: ${{ inputs.commenter_plan_path }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        PROJECT: ${{ inputs.project }}
      shell: bash
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e PROJECT \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -e COMMENTER_PLAN_FILE \
        -e COMMENTER_POST_PLAN_OUTPUTS \
        -v "$(pwd)"/:/workspace \
        -v "$GITHUB_OUTPUT":/github-ouput \
        kgrubb/terraform-pr-commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}

    - name: Run commenter image (non-plan)
      id: commenter
      if: ${{ inputs.commenter_type != 'plan' }}
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        PROJECT: ${{ inputs.project }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e PROJECT \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -v "$GITHUB_OUTPUT":/github-ouput \
        kgrubb/terraform-pr-commenter ${{ inputs.commenter_type }} ${{ inputs.commenter_exitcode }}
      shell: bash
