name: Deploy Docker Image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build, Tag, and Push Image
        run: |
          docker build \
            --build-arg TERRAFORM_VERSION=1.5.6 \
            -t ${{ secrets.DOCKER_USERNAME }}/terraform-pr-commenter .
          docker push ${{ secrets.DOCKER_USERNAME }}/terraform-pr-commenter
